### ISSUE TITLE
how to consume with proxy

### ISSUE THREAD

**Issue by marianfoo** [spreadsheetimporter/ui5-cc-spreadsheetimporter#565]
### Sample with fiori-tools-proxy

```yaml
        backend:
          - path: /sap
            url: <Cloud Connector or local URL>
            destination: <System Destination name if in BAS>
          - path: /resources/cc/spreadsheetimporter/v0_34_1
            destination: <System Destination name if in BAS>
            pathPrefix: /sap/bc/ui5_ui5/sap/<BSP NAME>/thirdparty/customcontrol/spreadsheetimporter/v0_34_1/
            url: <Cloud Connector or local URL>
```

**Comment by marianfoo** [comment]
include app index
/sap/bc/ui2/app_index/ui5_app_info?id=cc.spreadsheetimporter.v0_33_0

**Comment by marianfoo** [comment]
```yml 
   - name: ui5-middleware-simpleproxy
      afterMiddleware: compression
      mountPath: /resources/cc/spreadsheetimporter/v0_34_1/
      configuration:
        baseUri: "<SAP SYSTEM URL>/sap/bc/ui5_ui5/sap/<BSP NAME>/thirdparty/customcontrol/spreadsheetimporter/v0_34_1/"
        username: <SAP USERNAME>
        password: <SAP PASSWORD
        query:
          sap-client: '100'
```
